superhero_project/sidekicks/urls.py
from django.urls import path

from . import views

app_name="sidekicks"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:sidekick_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('edit<int:sidekick_id>/', views.edit, name='edit'),
    path('delete<int:sidekick_id>/', views.delete, name='delete'),
]

superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/')),
    path('sidekicks/', include('sidekicks.urls')),
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = "superheroes"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('edit<int:hero_id>/', views.edit, name='edit'),
    path('delete<int:hero_id>/', views.delete, name='delete'),
]

superhero_project/sidekicks/models.py
from django.db import models

# Create your models here.
class Sidekick(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    sidekick_to = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    description = models.CharField(max_length=750)

    def __str__(self):
        return self.name

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name

superhero_project/sidekicks/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import Sidekick


# Create your views here.
def index(request):
    all_sidekicks = Sidekick.objects.all
    context = {
        'all_sidekicks': all_sidekicks
    }
    return render(request, 'sidekicks/index.html', context)

def detail(request, sidekick_id):
    single_sidekick = Sidekick.objects.get(pk=sidekick_id)
    context = {
        'single_sidekick': single_sidekick
    }
    return render(request, 'sidekicks/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        sidekick_to = request.POST.get('sidekick_to')
        primary_ability = request.POST.get('primary_ability')
        description = request.POST.get('description')
        new_sidekick = Sidekick(name=name, alter_ego=alter_ego, sidekick_to=sidekick_to, primary_ability=primary_ability, description=description)
        new_sidekick.save()
        return HttpResponseRedirect(reverse('sidekicks:index'))
    else:
        return render(request, 'sidekicks/create.html')

def edit(request, sidekick_id):
    single_sidekick = Sidekick.objects.get(pk=sidekick_id)
    context = {
        'single_sidekick': single_sidekick
    }
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        sidekick_to = request.POST.get('sidekick_to')
        primary_ability = request.POST.get('primary_ability')
        description = request.POST.get('description')
        update_sidekick = Sidekick(id,name,alter_ego,sidekick_to,primary_ability, description)
        update_sidekick.save()
        return HttpResponseRedirect(reverse('sidekicks:index'))
    else:
        return render(request, 'sidekicks/edit.html', context)

def delete(request, sidekick_id):
    deleteMe = Sidekick.objects.get(pk=sidekick_id)
    deleteMe.delete()
    return HttpResponseRedirect(reverse('sidekicks:index'))

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        description = request.POST.get('description')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary_ability, secondary_ability=secondary_ability, catchphrase=catchphrase, description=description)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    if request.method == "POST":
        id = single_hero.id
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        description = request.POST.get('description')
        update_hero = Superhero(id, name, alter_ego, primary_ability, secondary_ability, catchphrase, description)
        update_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    deleteMe = Superhero.objects.get(pk=hero_id)
    deleteMe.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_project/sidekicks/templates/sidekicks/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Create New Sidekick</title>
</head>
<body>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
            <div class ="container container-fluid text-center pt-5 pb-5">
                <h1>You are creating a new sidekick</h1> 
                <p>It doesn't have to be an existing sidekick.  Feel free to make your own!.</p>
                <p><a href="/sidekicks">Or go back to the sidekick list.</a></p>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Name: </div><div class="col-md-10"><input type = "text" class="form-control" name="name" id ="name" ></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Alter Ego: </div><div class="col-md-10"><input type = "text" class="form-control" name="alter_ego" id="alter_ego"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Sidekick To: </div><div class="col-md-10"><input type="text" class="form-control" name ="sidekick_to" id = "sidekick_to"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Primary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name="primary_ability" id="primary_ability"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 pb-3 bg-success">Description: </div><div class="col-md-10 pb-3"><input type="text" class="form-control" name="description"  id="description"></div>   
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 "></div><div class="col-md-10"><input type="submit" value="Save Edits!"></div>
                </div>
            </form>
            </div>
        <div class="col-md-4 gx-4">
            {% load static %}
            <img src="{% static 'sidekicks/archie_predator.jpg' %}" class="img-thumbnail" alt="comic book cover with Archie and Predator">
        </div>
    </div>
</body>
</html>

superhero_project/sidekicks/templates/sidekicks/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Sidekick</title>
</head>
<body>
   
        
</body>
</html>

superhero_project/sidekicks/templates/sidekicks/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Hero Details</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class ="col-md-5 gx-4">
                {% load static %}
                <img src="{% static 'sidekicks/angled_comics.jpg' %}" class="img-thumbnail" alt="comics displayed at an angle" >
            </div>
            <div class="col-md-6 gx-4">
                <div class="container text-center">
                    <div class="row pb-4">
                        <h1>Selected Sidekick Details</h1>
                    </div>
                    <div class="row pb-2">
                        <p><a href="/sidekicks">Back to All Sidekicks</a></p>
                    </div>
                </div>
                <div class="row bg-success">
                    <div class="col-sm">Name:</div><div class="col-sm">{{single_sidekick.name}}</div>
                </div>
                <div class="row bg-success">
                    <div class = "col-sm">Alter Ego:</div><div class = "col-sm"> {{single_sidekick.alter_ego}}</div>
                </div>
                <div class="row bg-success">
                    <div class="col-sm">Sidekick To: </div><div class="col-sm">{{single_sidekick.sidekick_to}}</div>
                </div>
                <div class="row bg-success">
                    <div class = "col-sm">Primary Special Ability:</div><div class="col-sm"> {{single_sidekick.primary_ability}}</div>
                </div>
                <div class="row ft-2">
                    <div class="col-lg">{{single_sidekick.description}}</div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

superhero_project/sidekicks/templates/sidekicks/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Create New Hero</title>
</head>
<body>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
            <div class ="container container-fluid text-center pt-5 pb-5">
                <h1>You are editing {{single_sidekick.name}}. </h1> 
                <p>You can leave fields as is or you can change them as desired.</p>
                <p><a href="/sidekicks">Or go back to the list of sidekicks</a></p>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Name: </div><div class="col-md-10"><input type = "text" class="form-control" name="name" id ="name" value="{{single_sidekick.name}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Alter Ego: </div><div class="col-md-10"><input type = "text" class="form-control" name="alter_ego" id="alter_ego" value="{{single_sidekick.alter_ego}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Sidekick To: </div><div class="col-md-10"><input type="text" class="form-control" name ="sidekick_to" id = "sidekick_to" value="{{single_sidekick.sidekick_to}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-success">Primary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name="primary_ability" id="primary_ability" value="{{single_sidekick.primary_ability}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 pb-3 bg-success">Description: </div><div class="col-md-10 pb-3"><input type="text" class="form-control" name="description"  id="description" value="{{single_sidekick.description}}"></div>   
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 "></div><div class="col-md-10"><input type="submit" value="Save Edits!"></div>
                </div>
            </form>
            </div>
        <div class="col-md-4 gx-4">
            {% load static %}
            <img src="{% static 'sidekicks/comics_box.jpg' %}" class="img-thumbnail" alt="comics in a box">
        </div>
    </div>
</body>
</html>

superhero_project/sidekicks/templates/sidekicks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Sidekick Index</title>
</head>
<body>
    <div class="container-fluid bg-secondary">
        <h1 class="text-center">Everybody Loves Sidekicks (Especially Batman!)</h1>
        <h6 class = "text-center"><a href="/superheroes">HELP!! Sidekicks aren't cool! Take me back to superheroes!</a></h6>
    </div>
    <div class="container-fluid">
        <div class="row">
          <div class="col-6 ">

        <h1 class="text-center">Sidekick Index</h1>
        <p class="text-center"><a href="{% url 'sidekicks:create' %}">Create A New Sidekick For the List</a></p>
    
        <table class="table table-sm">
            <thead>
                <tr class="table-warning">
                    <th scope="col">Sidekick</th>
                    <th scope="col">Details</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                    {% for sidekick in all_sidekicks %}
                    <tr class="table-success">
                    <th scope="row">{{sidekick.name}}</th>
                    <td><a href="{% url 'sidekicks:detail' sidekick.id %}">Sidekick Details</a></td>
                    <td><a href="{% url 'sidekicks:edit' sidekick.id %}">Edit Sidekick</a></td>
                    <td><a href="{% url 'sidekicks:delete' sidekick.id %}">Delete Sidekick</a></td>
                    </tr>
                    {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-warning">
                    <div class="col"><th scope="col">Sidekick</th></div>
                    <div class="col"><th scope="col">Details</th></div>
                    <div class="col"><th scope="col">Edit</th></div>
                    <div class="col"><th scope="col">Delete</th></div>
                </tr>
            </tfoot>
        </table> 
    </div>  
<div class="col-5 pt-5">
    {% load static %}
    <img src="{% static 'sidekicks/scattered_comics.jpg' %}" class="img-fluid img-thumbnail" alt="Scattered Comics">
</div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Create New Hero</title>
</head>
<body>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
            <div class ="container container-fluid text-center pt-5 pb-5">
                <h1>You are creating a new hero</h1> 
                <p>It doesn't have to be an existing hero.  Feel free to make your own!.</p>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Name: </div><div class="col-md-10"><input type = "text" class="form-control" name="name" id ="name" ></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Alter Ego: </div><div class="col-md-10"><input type = "text" class="form-control" name="alter_ego" id="alter_ego"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Primary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name ="primary_ability" id = "primary_ability"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Secondary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name="secondary_ability" id="secondary_ability"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Catchphrase: </div><div class="col-md-10"><input type="text" class="form-control" name="catchphrase" id="catchphrase" ></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 pb-3 bg-info">Description: </div><div class="col-md-10 pb-3"><input type="text" class="form-control" name="description"  id="description"></div>   
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 "></div><div class="col-md-10"><input type="submit" value="Save Edits!"></div>
                </div>
            </form>
            </div>
        <div class="col-md-4 gx-4">
            {% load static %}
            <img src="{% static 'superheroes/superhero_shadow.png' %}" class="img-thumbnail" alt="flying superhero silhouette">
        </div>
    </div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Hero</title>
</head>
<body>
   
        
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Hero Details</title>
</head>
<body>
    <div class="container container-fluid text-center pt-5 pb-5"><h1>Selected Hero Details</h1></div>
   
    <div class="container-fluid">
        <div class="row">
            <div class ="col-md-4 gx-4">
                {% load static %}
                <img src="{% static 'superheroes/superhero_dude.png' %}" class="img-thumbnail" alt="proud superhero silhoutte" >
            </div>
            <div class="col-md-5 gx-4">
                <div class="row bg-info">
                    <div class="col-sm">Name:</div><div class="col-sm">{{single_hero.name}}</div>
                </div>
                <div class="row bg-info">
                    <div class = "col-sm">Alter Ego:</div><div class = "col-sm"> {{single_hero.alter_ego}}</div>
                </div>
                <div class="row bg-info">
                    <div class = "col-sm">Primary Special Ability:</div><div class="col-sm"> {{single_hero.primary_ability}}</div>
                </div>
                <div class="row bg-info">
                    <div class="col-sm">Secondary Special Ability: </div><div class="col-sm">{{single_hero.secondary_ability}}</div>
                </div>
                <div class="row bg-info">
                    <div class="col-sm">Catchphrase: </div><div class = "col-sm">"{{single_hero.catchphrase}}"</div>
                </div>
                <div class="row ft-2">
                    <div class="col-lg">{{single_hero.description}}</div>
                </div>
            </div>
            <div class="col-md-2 gx-4">
                {% load static %}
                <img src="{% static 'superheroes/superhero_flying.png' %}" class="img-thumbnail" alt="flying superhero silhouette">
            </div>
        </div>
    </div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Create New Hero</title>
</head>
<body>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
            <div class ="container container-fluid text-center pt-5 pb-5">
                <h1>You are editing {{single_hero.name}}. </h1> 
                <p>You can leave fields as is or you can change them as desired.</p>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Name: </div><div class="col-md-10"><input type = "text" class="form-control" name="name" id ="name" value="{{single_hero.name}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Alter Ego: </div><div class="col-md-10"><input type = "text" class="form-control" name="alter_ego" id="alter_ego" value="{{single_hero.alter_ego}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Primary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name ="primary_ability" id = "primary_ability" value="{{single_hero.primary_ability}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Secondary Ability: </div><div class="col-md-10"><input type="text" class="form-control" name="secondary_ability" id="secondary_ability" value="{{single_hero.secondary_ability}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 bg-info">Catchphrase: </div><div class="col-md-10"><input type="text" class="form-control" name="catchphrase" id="catchphrase" value="{{single_hero.catchphrase}}"></div>
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 pb-3 bg-info">Description: </div><div class="col-md-10 pb-3"><input type="text" class="form-control" name="description"  id="description" value="{{single_hero.description}}"></div>   
                </div>
                <div class="row">
                    <div class = "col-sm gx-4 "></div><div class="col-md-10"><input type="submit" value="Save Edits!"></div>
                </div>
            </form>
            </div>
        <div class="col-md-4 gx-4">
            {% load static %}
            <img src="{% static 'superheroes/batmanDuck.jpg' %}" class="img-thumbnail" alt="flying superhero silhouette">
        </div>
    </div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <title>Superhero Index</title>
</head>
<body>
    <div class="container-fluid bg-secondary">
        <div class="row">
            <div class="col-9">
            <p class="display-3 text-center">Everybody Loves Superheros</p> 
            </div>
            <div class="col-3 pt-5">
                <a href="/sidekicks">Or do you love sidekicks more?</a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
          <div class="col-6 ">

        <h1 class="text-center">Superhero Index</h1>
        <p class="text-center"><a href="{% url 'superheroes:create' %}">Create A New Hero For the List</a></p>
    
        <table class="table table-sm">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Superhero</th>
                    <th scope="col">Detail Link</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                    {% for hero in all_heroes %}
                    <tr class="table-info">
                    <th scope="row">{{hero.name}}</th>
                    <td><a href="{% url 'superheroes:detail' hero.id %}">Hero Details</a></td>
                    <td><a href="{% url 'superheroes:edit' hero.id %}">Edit Hero</a></td>
                    <td><a href="{% url 'superheroes:delete' hero.id %}">Delete Hero</a></td>
                    </tr>
                    {% endfor %}
            </tbody>
            <tfoot>
                <tr class="table-primary">
                    <div class="col"><th scope="col">Superhero</th></div>
                    <div class="col"><th scope="col">Detail Link</th></div>
                    <div class="col"><th scope="col">Edit</th></div>
                    <div class="col"><th scope="col">Delete</th></div>
                </tr>
            </tfoot>
        </table> 
    </div>  
<div class="col-6 pt-5">
    {% load static %}
    <img src="{% static 'superheroes/comics.jpg' %}" class="img-fluid img-thumbnail" alt="Scattered Comics">
</div>
</body>
</html>